INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','1597','NW','Lane Cove','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2036','NW','Matraville','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2055','NW','North Sydney','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2061','NW','Milsons Point','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2113','NW','North Ryde','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','21201','Maryland','Baltimore','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2138','NW','Rhodes','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2264','NW','Silverwater','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2300','NW','Newcastle','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2444','NW','Port Macquarie','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2450','NW','Coffs Harbour','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2500','NW','Wollongong','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','2777','NW','Springwood','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','3205','VI','South Melbourne','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','3280','VI','Warrnambool','UK');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','45202','OH','Cincinnati','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','4655','QU','Hervey Bay','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','4810','QU','Townsville','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','90012','CA','Los Angeles','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','90401','CA','Santa Monica','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','90505','CA','Torrance','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','90706','CA','Bellflower','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','91364','CA','Woodland Hills','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','91502','CA','Burbank','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','91791','CA','West Covina','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','91910','CA','Chula Vista','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','92020','CA','El Cajon','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','92102','CA','San Diego','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94010','CA','Burlingame','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94014','CA','Colma','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94519','CA','Concord','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94611','CA','Oakland','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94704','CA','Berkeley','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','94941','CA','Mill Valley','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','95062','CA','Santa Cruz','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','97034','OR','Lake Oswego','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','97045','OR','Oregon City','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','97205','OR','Portland','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','97330','OR','Corvallis','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','97355','OR','Lebanon','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98027','WA','Issaquah','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98033','WA','Kirkland','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98036','WA','Lynnwood','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98052','WA','Redmond','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98104','WA','Seattle','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98168','WA','Burien','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98201','WA','Everett','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98225','WA','Bellingham','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98270','WA','Marysville','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98284','WA','Sedro Woolley','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98312','WA','Bremerton','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98366','WA','Port Orchard','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98371','WA','Puyallup','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98501','WA','Olympia','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','98901','WA','Yakima','US');
INSERT INTO Venue(venue_name,address,zipcode,state,city,country) VALUES ('convention center','83156 barn street','99362','WA','Walla Walla','US');
