INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('A dive into Data Quality Services','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('A Dynamic World Demands Dynamic SQL','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('A Dynamic World Demands Dynamic SQL','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Absolute Introductory Session on SQL Server 2014 In-Memory Optimized Databases (Hekaton)','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('AlwaysOn: Improve reliability and reporting performance with one cool tech','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('An introduction to Data Mining','Course description goes here','Intermediate',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('An Introduction to Database Design','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Autogenerating a process data warehouse','Course description goes here','Advanced',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Automate your daily checklist with PBM and CMS','Course description goes here','Intermediate',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Automated Installing and Configuration of SQL2014/SQL2012 AlwaysOn Across Multiple Datacenters','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Automating Execution Plan Analysis','Course description goes here','Advanced',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Automating SQL Server using PowerShell','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Balanced Scorecards using SSRS','Course description goes here','Intermediate',60,4);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Baselines and Performance Monitoring with PAL','Course description goes here','Beginner',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Basic Database Design','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Basic Database Programming','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Become a BI Independent Consultant!','Course description goes here','Beginner',60,4);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Becoming a Top DBA--Learning Automation in SQL Server','Course description goes here','Beginner',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Best Practices Document','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Best Practices for Efficient SSRS Report Creation','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Biggest Loser: Database Edition','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Building a BI Solution in the Cloud','Course description goes here','Intermediate',60,4);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Building an Effective Data Warehouse Architecture','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Building an Effective Data Warehouse Architecture with the cloud and MPP','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Coffee Break','Course description goes here','Non-Technical',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Creating A Performance Health Repository - using MDW','Course description goes here','Beginner',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Creating efficient and effective SSRS BI Solutions','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Creating efficient and effective SSRS BI Solutions','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Data Partitioning','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Data Tier Application Testing with NUnit and Distributed Replay','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Database design for mere developers','Course description goes here','Intermediate',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Database design for mere developers','Course description goes here','Intermediate',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Database Design: Solving Problems Before they Start!','Course description goes here','Beginner',60,5);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Database Modeling and Design','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Database Virtualization and Drinking out of the Fire Hose','Course description goes here','Intermediate',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('DAX and the tabular model','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('DBA FOR DUMMIES','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Dealing With Difficult People','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Development Lifecycle with SQL Server Data Tools and DACFx','Course description goes here','Intermediate',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Did You Vote Today? A DBAs Guide to Cluster Quorum','Course description goes here','Advanced',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Dimensional Modeling Design Patterns: Beyond Basics','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Dimensional Modeling Design Patterns: Beyond Basics','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Diving Into Query Execution Plans','Course description goes here','Intermediate',60,5);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Dynamic SQL: Writing Efficient Queries on the Fly','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Easy Architecture Design for HA and DR','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Enhancing your career: Building your personal brand','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Establishing a SLA','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('ETL not ELT! Common mistakes and misconceptions about SSIS','Course description goes here','Advanced',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Event Kickoff and Networking','Course description goes here','Non-Technical',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Execution Plans: What Can You Do With Them?','Course description goes here','Intermediate',60,5);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Faster','Course description goes here','Intermediate',60,5);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Full Text Indexing Basics','Course description goes here','Beginner',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Get your Mining Model Predictions out to all','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Getting a job with Microsoft','Course description goes here','Non-Technical',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Graph Databases for SQL Server Professionals','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Hacking Expos� - Using SSL to Protect SQL Connections','Course description goes here','Intermediate',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Hacking the SSIS 2012 Catalog','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Hidden in plain sight: master your tools','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Highly Available SQL Server in Windows Azure IaaS','Course description goes here','Intermediate',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('How to Make a LOT More Money as a Consultant','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('How to Think Like the Engine','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Hybrid Cloud Scenarios with SQL Server 2014','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Hybrid Solutions: The Future of SQL Server Disaster Recovery','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Implementing Data Warehouse Patterns with the Microsoft BI Tools','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Inroduction to Triggers','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Integrating Reporting Services with SharePoint','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Integration Services (SSIS) for the DBA','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introducing Power BI','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introduction to Database Recovery','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introduction to High Availability with SQL Server','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introduction to Powershell for DBA''s','Course description goes here','Beginner',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introduction to SQL Server - Part 1','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Introduction to SQL Server - Part 2','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Is That A Failover Cluster On Your Laptop/Desktop?','Course description goes here','Intermediate',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Leaving the Windows Open','Course description goes here','Intermediate',60,2);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Lunch Break','Course description goes here','Non-Technical',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Lunchtime Keynote','Course description goes here','Non-Technical',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Master Data Services Best Practices','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Master Data Services Disaster Recovery','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Mind your language!! Cursors are a dirty word','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Modern Data Warehousing','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Monitoring Server health via Reporting Services dashboards','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Monitoring SQL Server using Extended Events','Course description goes here','Beginner',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Multidimensional vs Tabular - May the Best Model Win','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Murder They Wrote','Course description goes here','Intermediate',60,1);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Never Have to Say "Mayday!!!" Again','Course description goes here','Beginner',60,3);
INSERT INTO Course(title,description,difficulty,duration,fk_track_id) VALUES ('Now you see it! Now you don�t! Conjuring many reports utilizing only one SSRS report.','Course description goes here','Intermediate',60,1);
